apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: database
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 30s
  timeout: 30m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./database
  prune: false
  wait: true
