apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: mysql
spec:
  interval: 10m
  timeout: 30m0s
  releaseName: mysql
  chart:
    spec:
      chart: mysql
      version: 1.6.6
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: flux-system
  values:
    mysqlRootPassword: root
    image: mysql
    imageTag: 5.7.30@sha256:0563b36ec2d1a262f79e1d8562e61f642a0f64f93306d8a709047cdea0444d0a
